### ISSUE TITLE
Limits for the number of results requested

### ISSUE THREAD

**Issue by dnaranjo89** [Mariocj89/EchaloASuerte#54]
So far we were limiting the number of results requested only by html. Now I'm implementing some restrictions in the back end. Let me know what you think about them:

COIN: 10 (our site will only offer one at a time, but may be for the API....well, don't even know why someone would want to flip 10 coins...)
CARD: As many as the selected deck has
Dice: 20
RANDOM NUMBER: 50?
RANDOM ITEM FROM LIST: 50?
ASSOCIATION: I guess we need to limit the size of the list

**Comment by Mariocj89** [comment]
10 looks to low for me. We can speak later about that.

**Comment by dnaranjo89** [comment]
So some limits have been implemented in the form validation. Also there are some validations as well in the boms (is_feasible) which have to be modified in future
