### ISSUE TITLE
Lock submit button when processing

### ISSUE THREAD

**Issue by dnaranjo89** [Mariocj89/EchaloASuerte#67]
When clicking on submit while a request is being processed it runs into some errors. Execution keeps fine but we probably should fix this

**Comment by Mariocj89** [comment]
<input type="submit" onclick="this.disabled=true;this.value='Sending, please wait...';this.form.submit();" > We have test this in all browsers

**Comment by dnaranjo89** [comment]
Solved (68d79268ab1662b62224a0dea14e3720417f0866)
